CREATE TABLE post_label
(
    id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
    post_id BIGINT NOT NULL,
    label_id INT NOT NULL,
    CONSTRAINT postlabel_post_fkey FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT postlabel_label_fkey FOREIGN KEY (label_id) REFERENCES label(id) ON DELETE CASCADE ON UPDATE CASCADE
)